## Colors configuration
[colors.primary]
background = '#090a0c'
foreground = '#becdd2'

[colors.normal]
black = '#090a0c'
red = '#1B688A'
green = '#317291'
yellow = '#467A93'
blue = '#3F80A2'
magenta = '#538CA8'
cyan = '#6999AE'
white = '#becdd2'

[colors.bright]
black = '#858f93'
red = '#1B688A'
green = '#317291'
yellow = '#467A93'
blue = '#3F80A2'
magenta = '#538CA8'
cyan = '#6999AE'
white = '#becdd2'
