# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/Wallpapers/GWoz474XAAA2yX1.jpg'

# Special
background='#191c0d'
foreground='#e0e0df'
cursor='#e0e0df'

# Colors
color0='#191c0d'
color1='#728179'
color2='#AA9153'
color3='#768788'
color4='#989FA0'
color5='#B8BDBC'
color6='#B9C3C8'
color7='#e0e0df'
color8='#9c9c9c'
color9='#728179'
color10='#AA9153'
color11='#768788'
color12='#989FA0'
color13='#B8BDBC'
color14='#B9C3C8'
color15='#e0e0df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
