# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/Wallpapers/GhXdR0lawAA5ya_.jpg'

# Special
background='#090a0c'
foreground='#becdd2'
cursor='#becdd2'

# Colors
color0='#090a0c'
color1='#1B688A'
color2='#317291'
color3='#467A93'
color4='#3F80A2'
color5='#538CA8'
color6='#6999AE'
color7='#becdd2'
color8='#858f93'
color9='#1B688A'
color10='#317291'
color11='#467A93'
color12='#3F80A2'
color13='#538CA8'
color14='#6999AE'
color15='#becdd2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
